### PR TITLE
Add ability to use multiple, separate caches.

### PR DESCRIPTION
**Pull request by orbiteleven**
## What

Add ability to use multiple, separate caches

## Why

Suppose in one part of an app we want to limit results to `(regions)` (as an example: no specific addresses), but in another we're ok with having all results (including addresses). Using the same cache across these two pickers could result in an address being returned and selected for the first component.

## How

By providing an optional `cacheKey`, we can use different caches for the different result sets.

## Checklist

- [x] Documentation added
- [x] Tests
- [x] TypeScript definitions updated
- [x] Ready to be merged

### CODE REVIEW

**Comment by orbiteleven** [comment]
@wellyshen gentle nudge :)

**Comment by wellyshen** [comment]
@orbiteleven Thank you bro, can you help me to add the new property into the [d.ts](https://github.com/wellyshen/use-places-autocomplete/blob/master/src/use-places-autocomplete.d.ts#L11) file as well.

**Comment by orbiteleven** [comment]
Whoops. I mistakenly thought that file was generated. Done!

**Comment by wellyshen** [comment]
@all-contributors please add @orbiteleven  for code

**Comment by wellyshen** [comment]
@orbiteleven Awesome, [here you are](https://github.com/wellyshen/use-places-autocomplete/releases/tag/v1.11.0) bro.

**Pull request merged**
