### PR TITLE
Grammar update

### PR DESCRIPTION
**Pull request by kylekirkby**
Leverage -> Leveraging

### CODE REVIEW

**Comment by wellyshen** [comment]
@kylekirkby Thank you, very useful 👍

**Comment by kylekirkby** [comment]
> @kylekirkby Thank you, very useful +1

No problem! :)

**Comment by wellyshen** [comment]
all-contributors add @kylekirkby  doc

**Comment by wellyshen** [comment]
@all-contributors please add @kylekirkby  for doc

**Pull request merged**
